# Generated by Django 3.1.3 on 2020-11-26 19:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_empleado_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cv',
            field=ckeditor.fields.RichTextField(default='default'),
            preserve_default=False,
        ),
    ]
