# Generated by Django 3.1.3 on 2020-11-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_empleado_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='cv',
        ),
    ]
